const { catchAsyncError } = require("./catchAsyncError");

module.exports = {
    catchAsyncError
};